ALTER TABLE tenants ADD COLUMN IF NOT EXISTS security_deposit INTEGER DEFAULT 0;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS deposit_refunded INTEGER DEFAULT 0;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS deposit_note TEXT DEFAULT '';
