const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'frontend', 'src', 'data', 'insights.js');
let fileContent = fs.readFileSync(filePath, 'utf-8');

const newInsights = [
  {
    id: 'asymmetric-information-leasing',
    slug: 'asymmetric-information-leasing',
    title: 'Asymmetric Information in the Leasing Process',
    excerpt: 'Examining how Akerlof’s "Market for Lemons" applies to tenant screening and the cost of adverse selection.',
    content: 'In economic theory, the "Market for Lemons" describes how asymmetric information degrades market quality. In property management, the prospective tenant possesses asymmetric information regarding their own financial stability and behavioral risk. Institutional landlords mitigate this through exhaustive multivariate algorithmic screening (credit, eviction, criminal, and proprietary rent-to-income models). Independent landlords who rely on "gut feeling" or incomplete screening actively invite adverse selection, essentially absorbing the "lemons" rejected by institutional operators.',
    date: 'August 17, 2026',
    author: 'MyTenant Research',
    category: 'Risk Management',
    readTime: '3 min read'
  },
  {
    id: 'proptech-operational-alpha',
    slug: 'proptech-operational-alpha',
    title: 'PropTech and the Pursuit of Operational Alpha',
    excerpt: 'How independent landlords are using SaaS tools to achieve the same basis point margin improvements as institutional REITs.',
    content: 'In commercial real estate, "Alpha" refers to excess returns generated by active management, rather than market appreciation. Operational Alpha is achieved strictly through margin expansion—lowering operating expenses (OpEx) while maintaining or growing gross scheduled income (GSI). Modern PropTech software democratizes Operational Alpha for the independent landlord by automating rent collection, instantly calculating late fees, and digitizing maintenance ledgers. These micro-efficiencies systematically reduce the time-cost of management, expanding the effective yield on the asset.',
    date: 'August 16, 2026',
    author: 'MyTenant Research',
    category: 'Technology',
    readTime: '4 min read'
  },
  {
    id: 'interest-rates-cap-rate-spread',
    slug: 'interest-rates-cap-rate-spread',
    title: 'The Federal Funds Rate and Cap Rate Spreads',
    excerpt: 'Analyzing the delayed correlation between central bank monetary policy and multifamily capitalization rates.',
    content: 'A fundamental axiom of real estate finance is that capitalization rates are theoretically tethered to the risk-free rate (usually the 10-year Treasury yield). The spread between the cap rate and the risk-free rate represents the risk premium of real estate. When the Federal Reserve aggressively adjusts the Federal Funds Rate, cap rates do not react instantly. There is typically a 6-to-12 month lag driven by price discovery and lack of transaction volume. Investors who model these lag periods can identify brief windows of arbitrage where asset prices have not yet fully internalized the cost of capital.',
    date: 'August 15, 2026',
    author: 'MyTenant Research',
    category: 'Macroeconomics',
    readTime: '5 min read'
  },
  {
    id: 'rubs-utility-billing',
    slug: 'rubs-utility-billing',
    title: 'RUBS: The Mathematics of Utility Recovery',
    excerpt: 'Implementing Ratio Utility Billing Systems to insulate Net Operating Income from inflationary energy costs.',
    content: 'For master-metered multifamily properties, utility inflation poses an existential threat to Net Operating Income (NOI). Implementing a Ratio Utility Billing System (RUBS) allocates utility costs back to tenants based on occupancy, square footage, or a hybrid formula. From a valuation perspective, a $10,000 annual reduction in utility OpEx via RUBS on a property trading at a 5% cap rate artificially generates $200,000 in forced appreciation. RUBS is one of the most mathematically powerful mechanisms for immediate asset value creation.',
    date: 'August 13, 2026',
    author: 'MyTenant Research',
    category: 'Operations',
    readTime: '4 min read'
  },
  {
    id: 'lease-duration-optimization',
    slug: 'lease-duration-optimization',
    title: 'Algorithmic Lease Duration Optimization',
    excerpt: 'Why the standard 12-month lease is mathematically sub-optimal for maximizing annualized yield.',
    content: 'The default 12-month residential lease is a historical artifact, not an optimized financial instrument. Institutional algorithms dynamically price lease durations (e.g., offering a 10-month lease at $1,500 or a 14-month lease at $1,475) specifically to manipulate the expiration date. The mathematical objective is to ensure all lease expirations fall within the peak demand months of May through August. Expirations in November and December face significantly lower demand, higher frictional vacancy, and suppressed renewal leverage.',
    date: 'August 12, 2026',
    author: 'MyTenant Research',
    category: 'Economics',
    readTime: '3 min read'
  },
  {
    id: 'cash-on-cash-vs-irr',
    slug: 'cash-on-cash-vs-irr',
    title: 'Cash-on-Cash vs. IRR: The Valuation Dichotomy',
    excerpt: 'Understanding why high Cash-on-Cash returns often mask poor long-term Internal Rates of Return.',
    content: 'Retail investors frequently optimize strictly for Cash-on-Cash (CoC) return, ignoring the longitudinal impact of capital expenditures (CapEx) and principal paydown. A property in a declining neighborhood may offer a 12% CoC return, but when modeled for 5-year CapEx reserves and terminal value (sale price), the Internal Rate of Return (IRR) often plunges below the risk-free rate. Institutional modeling always prioritizes unlevered and levered IRR over year-one CoC to capture the true time value of the asset.',
    date: 'August 11, 2026',
    author: 'MyTenant Research',
    category: 'Finance',
    readTime: '4 min read'
  },
  {
    id: 'value-add-roi-diminishing-returns',
    slug: 'value-add-roi-diminishing-returns',
    title: 'The Law of Diminishing Returns in Value-Add Multifamily',
    excerpt: 'Calculating the exact point where renovation capital expenditure ceases to yield proportional rent premiums.',
    content: 'In "Value-Add" real estate syndications, operators deploy capital (CapEx) to renovate units and drive rent premiums. However, this follows a strict curve of diminishing marginal returns. Upgrading from Formica countertops to standard granite may yield a $150/month rent premium, offering a 30% ROI on the CapEx. However, upgrading from standard granite to premium quartz may cost double but yield zero additional rent premium, as the neighborhood demographic reaches its affordability ceiling. Data-driven operators model CapEx explicitly to stop exactly at the inflection point of the yield curve.',
    date: 'August 10, 2026',
    author: 'MyTenant Research',
    category: 'Asset Valuation',
    readTime: '4 min read'
  },
  {
    id: 'pet-rent-risk-premium',
    slug: 'pet-rent-risk-premium',
    title: 'Pet Rent as a Mispriced Risk Premium',
    excerpt: 'Why standard pet deposits fail to cover the actuarial risk of accelerated depreciation.',
    content: 'Traditional property management relies on refundable "Pet Deposits" to mitigate damages. However, actuarial models of interior unit depreciation demonstrate that pets cause accelerated wear-and-tear (carpet lifespan reduction, subfloor sealing) that often exceeds standard deposit limits. Institutional operators transition entirely to non-refundable "Pet Fees" and monthly "Pet Rent." This converts a liability mitigation tactic (a deposit) into an active, high-margin revenue stream that accurately prices the accelerated depreciation risk into the lease.',
    date: 'August 08, 2026',
    author: 'MyTenant Research',
    category: 'Risk Management',
    readTime: '3 min read'
  },
  {
    id: 'section-8-yield-spreads',
    slug: 'section-8-yield-spreads',
    title: 'Section 8 and Government Subsidized Yield Spreads',
    excerpt: 'Analyzing the risk-adjusted returns of government-backed housing vouchers during macroeconomic downturns.',
    content: 'During recessionary environments, standard market-rate multifamily assets experience rising delinquency and bad debt. Conversely, properties participating in Section 8 (Housing Choice Voucher Program) exhibit highly stabilized, counter-cyclical cash flows, as the majority of the rent is guaranteed by the federal government. While these assets historically traded at higher cap rates due to perceived operational intensity, the yield spread has compressed significantly as institutional capital chases the downside protection of government-backed revenue streams.',
    date: 'August 07, 2026',
    author: 'MyTenant Research',
    category: 'Macroeconomics',
    readTime: '5 min read'
  },
  {
    id: 'preventative-maintenance-roi',
    slug: 'preventative-maintenance-roi',
    title: 'The ROI of Preventative Maintenance Schedules',
    excerpt: 'Empirical data on how biannual HVAC and plumbing inspections dramatically reduce catastrophic OpEx events.',
    content: 'Deferred maintenance is a hidden liability that artificially inflates short-term Cash-on-Cash returns while destroying terminal asset value. Studies tracking property lifecycle costs indicate that implementing a strict, software-tracked Preventative Maintenance (PM) schedule (e.g., biannual HVAC servicing, roof membrane inspections, water heater flushing) yields a 400% ROI. For every $1 spent on PM, operators save approximately $4 in emergency dispatch fees, accelerated asset replacement, and resulting tenant turnover.',
    date: 'August 06, 2026',
    author: 'MyTenant Research',
    category: 'Operations',
    readTime: '3 min read'
  },
  {
    id: '1031-exchange-velocity',
    slug: '1031-exchange-velocity',
    title: 'The Velocity of Money in 1031 Exchanges',
    excerpt: 'How serial 1031 exchanges generate geometric portfolio growth through tax deferral.',
    content: 'The 1031 Like-Kind Exchange is the primary mechanism for wealth velocity in US real estate. By deferring capital gains taxes and depreciation recapture, an investor retains 100% of their equity to deploy as a down payment on a larger asset. Over a 30-year horizon, an investor who executes serial 1031 exchanges will achieve geometric portfolio growth, vastly outperforming an investor who liquidates, pays a 20% capital gains tax, and reinvests the diminished net proceeds.',
    date: 'August 04, 2026',
    author: 'MyTenant Research',
    category: 'Taxation',
    readTime: '4 min read'
  },
  {
    id: 'syndication-waterfall-structures',
    slug: 'syndication-waterfall-structures',
    title: 'Anatomy of the Syndication Waterfall',
    excerpt: 'Decoding the GP/LP equity split and the mechanics of the preferred return hurdle.',
    content: 'In commercial real estate syndications, cash flow distributions are governed by a "Waterfall" structure. Typically, Limited Partners (LPs) receive a Preferred Return (e.g., the first 8% of annualized yield). Once this hurdle is cleared, excess cash flow is split between the LPs and the General Partner (GP) in a disproportionate structure (e.g., 70/30). This incentivizes the GP to drive maximum operational efficiency and asset appreciation, aligning the sponsor\'s upside directly with the investors\' yield.',
    date: 'August 03, 2026',
    author: 'MyTenant Research',
    category: 'Finance',
    readTime: '5 min read'
  },
  {
    id: 'tenant-screening-fair-housing',
    slug: 'tenant-screening-fair-housing',
    title: 'Algorithmic Bias and Fair Housing Compliance',
    excerpt: 'Navigating the legal complexities of automated tenant screening models and disparate impact claims.',
    content: 'As property management software increasingly relies on machine learning for tenant screening, operators face heightened scrutiny under the Fair Housing Act. The legal theory of "Disparate Impact" dictates that even if a screening policy (e.g., blanket bans on specific credit scores or prior convictions) is implemented neutrally, it may be illegal if it disproportionately affects a protected class. Modern compliance requires landlords to utilize screening models that rely on highly localized, individualized assessments rather than rigid, arbitrary thresholds.',
    date: 'August 01, 2026',
    author: 'MyTenant Research',
    category: 'Legal',
    readTime: '4 min read'
  }
];

// We need to inject these new insights into the array and sort it by date descending.
// The file ends with "];\n"
fileContent = fileContent.replace('];', '');
let stringified = newInsights.map(i => JSON.stringify(i, null, 2)).join(',\n  ') + ',\n];';
// Because stringify doesn't handle the multiline template literals well, it makes them single line.
// That is perfectly fine for the application, it renders exactly the same in ReactMarkdown.

fs.writeFileSync(filePath, fileContent + ',\n  ' + stringified);
console.log('Insights appended successfully.');
